/**
 * Gateway action signing — cross-language byte-compatibility tests.
 *
 * The fixed vectors below were generated by the gateway's Go signer
 * (poker-vm pvm/go/gateway/auth: dcrd secp256k1 SignCompact over the
 * EIP-191 keccak256 digest). Both ethers.js and dcrd use RFC6979
 * deterministic nonces, so the signatures must match BYTE FOR BYTE.
 * If these tests fail after touching buildActionPayload or the signing
 * path, gateway-side verification of FE actions is broken.
 */
import { ethers } from "ethers";

import { buildActionPayload, signActionMessage } from "../utils/cosmos/signing";
import { getCosmosMnemonic } from "../utils/cosmos/storage";

jest.mock("../utils/cosmos/storage");
const mockedGetMnemonic = getCosmosMnemonic as jest.MockedFunction<typeof getCosmosMnemonic>;

// NOT a real account — fixed throwaway key used by the Go vector generator.
const VECTOR_PRIVATE_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";

const VECTORS = [
    {
        payload: "pokerchain-action:game-1:call:7:1000000:1717600000000:",
        signature:
            "0x7cc70101d16ab50fb42882f886e4f34276cf26bdc2d45b4e79b862ccdc1a47de0a8914ca52a079039d4457aee88a1951936992b180d3bbcf6d7c6c7a7f8f1d0e1b"
    },
    {
        payload: "pokerchain-action:game-1:join:1:100000000000000000000:1717600000000:seat=2",
        signature:
            "0x39a612ebedbafcee7d4e20c85e6e60062ac80f941c1df50cb618b6d07e9fc442523ef90ccaa77bbf6055e8bda4b9fd0ed7c1304f73af78c6f8fedcfb4c5cda1f1c"
    }
];

const COSMOS_HD_PATH = "m/44'/118'/0'/0/0";
const TEST_MNEMONIC = "test test test test test test test test test test test junk";

describe("buildActionPayload", () => {
    it("matches the gateway's canonical payload format exactly", () => {
        expect(buildActionPayload("game-1", "call", 7, "1000000", 1717600000000, "")).toBe(VECTORS[0].payload);
        expect(buildActionPayload("game-1", "join", 1, "100000000000000000000", 1717600000000, "seat=2")).toBe(VECTORS[1].payload);
    });

    it("binds every field — changing any field changes the payload", () => {
        const base = buildActionPayload("g", "call", 1, "100", 42, "seat=1");
        const variants = [
            buildActionPayload("g2", "call", 1, "100", 42, "seat=1"),
            buildActionPayload("g", "raise", 1, "100", 42, "seat=1"),
            buildActionPayload("g", "call", 2, "100", 42, "seat=1"),
            buildActionPayload("g", "call", 1, "101", 42, "seat=1"),
            buildActionPayload("g", "call", 1, "100", 43, "seat=1"),
            buildActionPayload("g", "call", 1, "100", 42, "seat=2")
        ];
        for (const variant of variants) {
            expect(variant).not.toBe(base);
        }
    });
});

describe("EIP-191 signature byte-compatibility with the Go gateway signer", () => {
    it.each(VECTORS)("ethers signMessage reproduces the Go signature for $payload", async ({ payload, signature }) => {
        const wallet = new ethers.Wallet(VECTOR_PRIVATE_KEY);
        await expect(wallet.signMessage(payload)).resolves.toBe(signature);
    });
});

describe("signActionMessage", () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it("derives via the Cosmos HD path and signs the canonical payload (Go-vector exact)", async () => {
        mockedGetMnemonic.mockReturnValue(TEST_MNEMONIC);

        // HDNodeWallet.fromPhrase is unavailable under jest's crypto shims
        // (ethers v6 Buffer quirk), so pin the derivation to the vector key
        // and assert (a) the derivation args and (b) the EXACT signature the
        // Go gateway signer produced for this payload.
        const vectorWallet = new ethers.Wallet(VECTOR_PRIVATE_KEY);
        const fromPhrase = jest.spyOn(ethers.HDNodeWallet, "fromPhrase").mockReturnValue(vectorWallet as unknown as ethers.HDNodeWallet);

        const signature = await signActionMessage("game-1", "call", 7, "1000000", 1717600000000, "");

        expect(fromPhrase).toHaveBeenCalledWith(TEST_MNEMONIC, undefined, COSMOS_HD_PATH);
        expect(signature).toBe(VECTORS[0].signature);
    });

    it("returns null when no mnemonic is stored", async () => {
        mockedGetMnemonic.mockReturnValue(null);

        await expect(signActionMessage("game-1", "fold", 1, "0", 1717600000000, "")).resolves.toBeNull();
    });
});
